// go get -u google.golang.org/grpc
// go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
// go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
// protoc --go_out=. --go-grpc_out=. proto/anomaly_identifier.proto
// go mod vendor

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: anomaly_identifier.proto

package anomaly_identifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Services int32

const (
	Services_PGSQL Services = 0
)

// Enum value maps for Services.
var (
	Services_name = map[int32]string{
		0: "PGSQL",
	}
	Services_value = map[string]int32{
		"PGSQL": 0,
	}
)

func (x Services) Enum() *Services {
	p := new(Services)
	*p = x
	return p
}

func (x Services) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Services) Descriptor() protoreflect.EnumDescriptor {
	return file_anomaly_identifier_proto_enumTypes[0].Descriptor()
}

func (Services) Type() protoreflect.EnumType {
	return &file_anomaly_identifier_proto_enumTypes[0]
}

func (x Services) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Services.Descriptor instead.
func (Services) EnumDescriptor() ([]byte, []int) {
	return file_anomaly_identifier_proto_rawDescGZIP(), []int{0}
}

type AnomalyIdentifierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service          Services `protobuf:"varint,1,opt,name=service,proto3,enum=anomaly_identifier.Services" json:"service,omitempty"`
	Field            string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	RestrictiveQuery string   `protobuf:"bytes,3,opt,name=restrictiveQuery,proto3" json:"restrictiveQuery,omitempty"`
	Table            string   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *AnomalyIdentifierRequest) Reset() {
	*x = AnomalyIdentifierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anomaly_identifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnomalyIdentifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyIdentifierRequest) ProtoMessage() {}

func (x *AnomalyIdentifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anomaly_identifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyIdentifierRequest.ProtoReflect.Descriptor instead.
func (*AnomalyIdentifierRequest) Descriptor() ([]byte, []int) {
	return file_anomaly_identifier_proto_rawDescGZIP(), []int{0}
}

func (x *AnomalyIdentifierRequest) GetService() Services {
	if x != nil {
		return x.Service
	}
	return Services_PGSQL
}

func (x *AnomalyIdentifierRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AnomalyIdentifierRequest) GetRestrictiveQuery() string {
	if x != nil {
		return x.RestrictiveQuery
	}
	return ""
}

func (x *AnomalyIdentifierRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type AnomalyIdentifierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnomalyIds []int32 `protobuf:"varint,1,rep,packed,name=anomaly_ids,json=anomalyIds,proto3" json:"anomaly_ids,omitempty"`
}

func (x *AnomalyIdentifierResponse) Reset() {
	*x = AnomalyIdentifierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anomaly_identifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnomalyIdentifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyIdentifierResponse) ProtoMessage() {}

func (x *AnomalyIdentifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anomaly_identifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyIdentifierResponse.ProtoReflect.Descriptor instead.
func (*AnomalyIdentifierResponse) Descriptor() ([]byte, []int) {
	return file_anomaly_identifier_proto_rawDescGZIP(), []int{1}
}

func (x *AnomalyIdentifierResponse) GetAnomalyIds() []int32 {
	if x != nil {
		return x.AnomalyIds
	}
	return nil
}

var File_anomaly_identifier_proto protoreflect.FileDescriptor

var file_anomaly_identifier_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x6e, 0x6f, 0x6d,
	0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0xaa,
	0x01, 0x0a, 0x18, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61,
	0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x76, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x40, 0x0a, 0x19, 0x41,
	0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0b, 0x61, 0x6e, 0x6f, 0x6d,
	0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10,
	0x01, 0x52, 0x0a, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x73, 0x2a, 0x15, 0x0a,
	0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x47, 0x53,
	0x51, 0x4c, 0x10, 0x00, 0x32, 0x85, 0x01, 0x0a, 0x18, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x69, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x2e,
	0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x2e, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x6e,
	0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x2e, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14,
	0x2e, 0x2f, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_anomaly_identifier_proto_rawDescOnce sync.Once
	file_anomaly_identifier_proto_rawDescData = file_anomaly_identifier_proto_rawDesc
)

func file_anomaly_identifier_proto_rawDescGZIP() []byte {
	file_anomaly_identifier_proto_rawDescOnce.Do(func() {
		file_anomaly_identifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_anomaly_identifier_proto_rawDescData)
	})
	return file_anomaly_identifier_proto_rawDescData
}

var file_anomaly_identifier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_anomaly_identifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anomaly_identifier_proto_goTypes = []interface{}{
	(Services)(0),                     // 0: anomaly_identifier.Services
	(*AnomalyIdentifierRequest)(nil),  // 1: anomaly_identifier.AnomalyIdentifierRequest
	(*AnomalyIdentifierResponse)(nil), // 2: anomaly_identifier.AnomalyIdentifierResponse
}
var file_anomaly_identifier_proto_depIdxs = []int32{
	0, // 0: anomaly_identifier.AnomalyIdentifierRequest.service:type_name -> anomaly_identifier.Services
	1, // 1: anomaly_identifier.AnomalyIdentifierService.Generate:input_type -> anomaly_identifier.AnomalyIdentifierRequest
	2, // 2: anomaly_identifier.AnomalyIdentifierService.Generate:output_type -> anomaly_identifier.AnomalyIdentifierResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anomaly_identifier_proto_init() }
func file_anomaly_identifier_proto_init() {
	if File_anomaly_identifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_anomaly_identifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnomalyIdentifierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anomaly_identifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnomalyIdentifierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_anomaly_identifier_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anomaly_identifier_proto_goTypes,
		DependencyIndexes: file_anomaly_identifier_proto_depIdxs,
		EnumInfos:         file_anomaly_identifier_proto_enumTypes,
		MessageInfos:      file_anomaly_identifier_proto_msgTypes,
	}.Build()
	File_anomaly_identifier_proto = out.File
	file_anomaly_identifier_proto_rawDesc = nil
	file_anomaly_identifier_proto_goTypes = nil
	file_anomaly_identifier_proto_depIdxs = nil
}
