// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: anomaly_identifier.proto

package anomaly_identifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnomalyIdentifierServiceClient is the client API for AnomalyIdentifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnomalyIdentifierServiceClient interface {
	Generate(ctx context.Context, in *AnomalyIdentifierRequest, opts ...grpc.CallOption) (*AnomalyIdentifierResponse, error)
}

type anomalyIdentifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnomalyIdentifierServiceClient(cc grpc.ClientConnInterface) AnomalyIdentifierServiceClient {
	return &anomalyIdentifierServiceClient{cc}
}

func (c *anomalyIdentifierServiceClient) Generate(ctx context.Context, in *AnomalyIdentifierRequest, opts ...grpc.CallOption) (*AnomalyIdentifierResponse, error) {
	out := new(AnomalyIdentifierResponse)
	err := c.cc.Invoke(ctx, "/anomaly_identifier.AnomalyIdentifierService/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnomalyIdentifierServiceServer is the server API for AnomalyIdentifierService service.
// All implementations must embed UnimplementedAnomalyIdentifierServiceServer
// for forward compatibility
type AnomalyIdentifierServiceServer interface {
	Generate(context.Context, *AnomalyIdentifierRequest) (*AnomalyIdentifierResponse, error)
	mustEmbedUnimplementedAnomalyIdentifierServiceServer()
}

// UnimplementedAnomalyIdentifierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnomalyIdentifierServiceServer struct {
}

func (UnimplementedAnomalyIdentifierServiceServer) Generate(context.Context, *AnomalyIdentifierRequest) (*AnomalyIdentifierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedAnomalyIdentifierServiceServer) mustEmbedUnimplementedAnomalyIdentifierServiceServer() {
}

// UnsafeAnomalyIdentifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnomalyIdentifierServiceServer will
// result in compilation errors.
type UnsafeAnomalyIdentifierServiceServer interface {
	mustEmbedUnimplementedAnomalyIdentifierServiceServer()
}

func RegisterAnomalyIdentifierServiceServer(s grpc.ServiceRegistrar, srv AnomalyIdentifierServiceServer) {
	s.RegisterService(&AnomalyIdentifierService_ServiceDesc, srv)
}

func _AnomalyIdentifierService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnomalyIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyIdentifierServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anomaly_identifier.AnomalyIdentifierService/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyIdentifierServiceServer).Generate(ctx, req.(*AnomalyIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnomalyIdentifierService_ServiceDesc is the grpc.ServiceDesc for AnomalyIdentifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnomalyIdentifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anomaly_identifier.AnomalyIdentifierService",
	HandlerType: (*AnomalyIdentifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _AnomalyIdentifierService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anomaly_identifier.proto",
}
