// go get -u google.golang.org/grpc
// go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
// go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
// protoc --go_out=. --go-grpc_out=. proto/anomaly_identifier.proto
// go mod vendor

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: anomaly_identifier.proto

package anomaly_identifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service int32

const (
	Service_PGSQL Service = 0
)

// Enum value maps for Service.
var (
	Service_name = map[int32]string{
		0: "PGSQL",
	}
	Service_value = map[string]int32{
		"PGSQL": 0,
	}
)

func (x Service) Enum() *Service {
	p := new(Service)
	*p = x
	return p
}

func (x Service) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service) Descriptor() protoreflect.EnumDescriptor {
	return file_anomaly_identifier_proto_enumTypes[0].Descriptor()
}

func (Service) Type() protoreflect.EnumType {
	return &file_anomaly_identifier_proto_enumTypes[0]
}

func (x Service) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service.Descriptor instead.
func (Service) EnumDescriptor() ([]byte, []int) {
	return file_anomaly_identifier_proto_rawDescGZIP(), []int{0}
}

type ComparisonSign int32

const (
	ComparisonSign_MORE        ComparisonSign = 0
	ComparisonSign_LESS        ComparisonSign = 1
	ComparisonSign_EQUALS      ComparisonSign = 2
	ComparisonSign_MORE_EQUALS ComparisonSign = 3
	ComparisonSign_LESS_EQUALS ComparisonSign = 4
)

// Enum value maps for ComparisonSign.
var (
	ComparisonSign_name = map[int32]string{
		0: "MORE",
		1: "LESS",
		2: "EQUALS",
		3: "MORE_EQUALS",
		4: "LESS_EQUALS",
	}
	ComparisonSign_value = map[string]int32{
		"MORE":        0,
		"LESS":        1,
		"EQUALS":      2,
		"MORE_EQUALS": 3,
		"LESS_EQUALS": 4,
	}
)

func (x ComparisonSign) Enum() *ComparisonSign {
	p := new(ComparisonSign)
	*p = x
	return p
}

func (x ComparisonSign) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonSign) Descriptor() protoreflect.EnumDescriptor {
	return file_anomaly_identifier_proto_enumTypes[1].Descriptor()
}

func (ComparisonSign) Type() protoreflect.EnumType {
	return &file_anomaly_identifier_proto_enumTypes[1]
}

func (x ComparisonSign) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonSign.Descriptor instead.
func (ComparisonSign) EnumDescriptor() ([]byte, []int) {
	return file_anomaly_identifier_proto_rawDescGZIP(), []int{1}
}

type Limitation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field          string         `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	ComparisonSign ComparisonSign `protobuf:"varint,2,opt,name=comparisonSign,proto3,enum=anomaly_identifier.ComparisonSign" json:"comparisonSign,omitempty"`
	Value          string         `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Limitation) Reset() {
	*x = Limitation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anomaly_identifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Limitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limitation) ProtoMessage() {}

func (x *Limitation) ProtoReflect() protoreflect.Message {
	mi := &file_anomaly_identifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limitation.ProtoReflect.Descriptor instead.
func (*Limitation) Descriptor() ([]byte, []int) {
	return file_anomaly_identifier_proto_rawDescGZIP(), []int{0}
}

func (x *Limitation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Limitation) GetComparisonSign() ComparisonSign {
	if x != nil {
		return x.ComparisonSign
	}
	return ComparisonSign_MORE
}

func (x *Limitation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AnomalyIdentifierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service    Service       `protobuf:"varint,1,opt,name=service,proto3,enum=anomaly_identifier.Service" json:"service,omitempty"`
	Field      string        `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Limitation []*Limitation `protobuf:"bytes,3,rep,name=limitation,proto3" json:"limitation,omitempty"`
	Table      string        `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *AnomalyIdentifierRequest) Reset() {
	*x = AnomalyIdentifierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anomaly_identifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnomalyIdentifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyIdentifierRequest) ProtoMessage() {}

func (x *AnomalyIdentifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anomaly_identifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyIdentifierRequest.ProtoReflect.Descriptor instead.
func (*AnomalyIdentifierRequest) Descriptor() ([]byte, []int) {
	return file_anomaly_identifier_proto_rawDescGZIP(), []int{1}
}

func (x *AnomalyIdentifierRequest) GetService() Service {
	if x != nil {
		return x.Service
	}
	return Service_PGSQL
}

func (x *AnomalyIdentifierRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AnomalyIdentifierRequest) GetLimitation() []*Limitation {
	if x != nil {
		return x.Limitation
	}
	return nil
}

func (x *AnomalyIdentifierRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type AnomalyIdentifierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnomalyIds []int64 `protobuf:"varint,1,rep,packed,name=anomaly_ids,json=anomalyIds,proto3" json:"anomaly_ids,omitempty"`
}

func (x *AnomalyIdentifierResponse) Reset() {
	*x = AnomalyIdentifierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anomaly_identifier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnomalyIdentifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyIdentifierResponse) ProtoMessage() {}

func (x *AnomalyIdentifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anomaly_identifier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyIdentifierResponse.ProtoReflect.Descriptor instead.
func (*AnomalyIdentifierResponse) Descriptor() ([]byte, []int) {
	return file_anomaly_identifier_proto_rawDescGZIP(), []int{2}
}

func (x *AnomalyIdentifierResponse) GetAnomalyIds() []int64 {
	if x != nil {
		return x.AnomalyIds
	}
	return nil
}

var File_anomaly_identifier_proto protoreflect.FileDescriptor

var file_anomaly_identifier_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x6e, 0x6f, 0x6d,
	0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x84,
	0x01, 0x0a, 0x0a, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x4a, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f,
	0x6e, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x61, 0x6e,
	0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x52,
	0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xbd, 0x01, 0x0a, 0x18, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c,
	0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x3e, 0x0a, 0x0a, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x40, 0x0a, 0x19, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x23, 0x0a, 0x0b, 0x61, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x61, 0x6e, 0x6f,
	0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x73, 0x2a, 0x14, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x47, 0x53, 0x51, 0x4c, 0x10, 0x00, 0x2a, 0x52, 0x0a,
	0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x12,
	0x08, 0x0a, 0x04, 0x4d, 0x4f, 0x52, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x53,
	0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x10, 0x02, 0x12,
	0x0f, 0x0a, 0x0b, 0x4d, 0x4f, 0x52, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x10, 0x03,
	0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x53, 0x10,
	0x04, 0x32, 0x85, 0x01, 0x0a, 0x18, 0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69,
	0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x2e, 0x61, 0x6e, 0x6f,
	0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e,
	0x41, 0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x6e, 0x6f, 0x6d, 0x61,
	0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x41, 0x6e,
	0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x61,
	0x6e, 0x6f, 0x6d, 0x61, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_anomaly_identifier_proto_rawDescOnce sync.Once
	file_anomaly_identifier_proto_rawDescData = file_anomaly_identifier_proto_rawDesc
)

func file_anomaly_identifier_proto_rawDescGZIP() []byte {
	file_anomaly_identifier_proto_rawDescOnce.Do(func() {
		file_anomaly_identifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_anomaly_identifier_proto_rawDescData)
	})
	return file_anomaly_identifier_proto_rawDescData
}

var file_anomaly_identifier_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_anomaly_identifier_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_anomaly_identifier_proto_goTypes = []interface{}{
	(Service)(0),                      // 0: anomaly_identifier.Service
	(ComparisonSign)(0),               // 1: anomaly_identifier.ComparisonSign
	(*Limitation)(nil),                // 2: anomaly_identifier.Limitation
	(*AnomalyIdentifierRequest)(nil),  // 3: anomaly_identifier.AnomalyIdentifierRequest
	(*AnomalyIdentifierResponse)(nil), // 4: anomaly_identifier.AnomalyIdentifierResponse
}
var file_anomaly_identifier_proto_depIdxs = []int32{
	1, // 0: anomaly_identifier.Limitation.comparisonSign:type_name -> anomaly_identifier.ComparisonSign
	0, // 1: anomaly_identifier.AnomalyIdentifierRequest.service:type_name -> anomaly_identifier.Service
	2, // 2: anomaly_identifier.AnomalyIdentifierRequest.limitation:type_name -> anomaly_identifier.Limitation
	3, // 3: anomaly_identifier.AnomalyIdentifierService.Generate:input_type -> anomaly_identifier.AnomalyIdentifierRequest
	4, // 4: anomaly_identifier.AnomalyIdentifierService.Generate:output_type -> anomaly_identifier.AnomalyIdentifierResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_anomaly_identifier_proto_init() }
func file_anomaly_identifier_proto_init() {
	if File_anomaly_identifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_anomaly_identifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Limitation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anomaly_identifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnomalyIdentifierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anomaly_identifier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnomalyIdentifierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_anomaly_identifier_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anomaly_identifier_proto_goTypes,
		DependencyIndexes: file_anomaly_identifier_proto_depIdxs,
		EnumInfos:         file_anomaly_identifier_proto_enumTypes,
		MessageInfos:      file_anomaly_identifier_proto_msgTypes,
	}.Build()
	File_anomaly_identifier_proto = out.File
	file_anomaly_identifier_proto_rawDesc = nil
	file_anomaly_identifier_proto_goTypes = nil
	file_anomaly_identifier_proto_depIdxs = nil
}
